name: pos_app
description: "Clothes App - Flutter e-commerce"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
