#!/usr/bin/env bash

echo "Starting Project Directory Verification"
echo ""
for i in alpha beta gamma; do
    echo "-----------------------"
    echo "Check status for dir $i"
    echo ""
    if [ -e /tmp/project_$i ]; then
        echo "[OK] dir already exist in /tmp/project_$i"
    else
        echo "[MISSING] creating dir at /tmp/project_$i"
        mkdir /tmp/project_$i
    fi
done
