#!/usr/bin/env bash

set -e

PASS="linux"
INPUT=""

while [[ $INPUT != $PASS ]]; do
    echo ""
    read -s -p "Enter password: " INPUT
    if [[ $INPUT != $PASS ]]; then
        echo -e "\nincorrect password"
    fi
done

echo -e "\nAccess Granted!"

# -----------------------------------------------

# COUNT=5
#
# while [[ $COUNT -gt 0 ]]; do
#     echo "Countdown $COUNT"
#     sleep 1
#     COUNT=$((COUNT-1))
# done
#
# echo "Boom!"

# -----------------------------------------------

# while [[ 1 -gt 2 ]]; do
#     echo "Hello, World!"
# done

# -----------------------------------------------

# while true; do
#     echo " === SYSTEM UTILITY MENU === "
#     echo " 1. Display date and time"
#     echo " 2. Show stroage usage"
#     echo " 3. Exit"
#     echo ""
#
#     read -rp " Selete option [1-3]: " CHOICE
#
#     if [[ $CHOICE -eq 1 ]]; then
#         echo " =========================== "
#         date
#         echo " =========================== "
#     elif [[ $CHOICE -eq 2 ]]; then
#         echo " =========================== "
#         df -h /
#         echo " =========================== "
#     else
#         echo "Exit Program. Good bye!"
#         break;
#     fi
# done

# -----------------------------------------------

# CORRECT_PIN_CODE=1234
#
# read -sp "Set 4 digit pin code: " CORRECT_PIN_CODE
# echo
# while true; do
#     read -sp "Enter 4 digit pin code: " PIN_CODE
#     echo
#     if [[ $PIN_CODE -eq $CORRECT_PIN_CODE ]]; then
#         echo "Access Granted"
#         break;
#     fi
#     echo -e "Access Denied. \nPlease try again"
# done

# -----------------------------------------------
# 142.250.198.142

# IP=""
# read -p "Enter IP Address: " IP
#
# echo -e "Mornitoring $IP ...\nwaiting for host to come online"
#
# while true; do
#     ping -c 3 $IP
#
#     if [[ $? -eq 0 ]]; then
#         echo "[SUCCESS] Host $IP is online!"
#         break
#     fi
#     echo -e "\n[FAILED] Host $IP can't be reach\nTry again\n"
# done

# -----------------------------------------------
