#!/usr/bin/env bash

read -p "Please enter the number from 1 - 100: " NUM

if [ $NUM -lt 100 ]; then
    echo "The number is smaller than 100"
elif [ $NUM -gt 100 ]; then
    echo "The number is bigger 100"
else
    echo "The number is equal to 100"
fi
