#!/usr/bin/env bash

DATE=$(date | awk '{print $1}')

if [ $DATE == Fri ]; then
    echo "Today is $DATE"
else
    echo "Today is not $DATE"
fi

echo "What is your name?"
read NAME

echo "Do you like working in IT?"
read ANSWER

if [ $ANSWER == "yes" ] || [ $ANSWER == 'y' ]; then
    echo "I like working in IT"
else
    echo "I don't like working in IT"
fi
