// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      return android;
    case TargetPlatform.iOS:
      return ios;
    case TargetPlatform.macOS:
      return macos;
    case TargetPlatform.windows:
      return windows;
    case TargetPlatform.linux:
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    default:
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMxsjZy3lCqnSeI5cRoEyUqoDGP4UBsSA',
    appId: '1:964323096567:web:a394f46427b83be012e0f2',
    messagingSenderId: '964323096567',
    projectId: 'first-789fb',
    authDomain: 'first-789fb.firebaseapp.com',
    databaseURL: 'https://first-789fb-default-rtdb.firebaseio.com',
    storageBucket: 'first-789fb.firebasestorage.app',
    measurementId: 'G-KFWKEEQM6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-FOV6_Xkz0rMnUYF0hbE5GOkGkZy7zE',
    appId: '1:964323096567:android:011c991f11fc23e612e0f2',
    messagingSenderId: '964323096567',
    projectId: 'first-789fb',
    databaseURL: 'https://first-789fb-default-rtdb.firebaseio.com',
    storageBucket: 'first-789fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTrCVOkWMHzEwwtNvRWW_pt3-AZv2v_-I',
    appId: '1:964323096567:ios:74317ae8b1b01e3812e0f2',
    messagingSenderId: '964323096567',
    projectId: 'first-789fb',
    databaseURL: 'https://first-789fb-default-rtdb.firebaseio.com',
    storageBucket: 'first-789fb.firebasestorage.app',
    iosBundleId: 'com.example.clothApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTrCVOkWMHzEwwtNvRWW_pt3-AZv2v_-I',
    appId: '1:964323096567:ios:74317ae8b1b01e3812e0f2',
    messagingSenderId: '964323096567',
    projectId: 'first-789fb',
    databaseURL: 'https://first-789fb-default-rtdb.firebaseio.com',
    storageBucket: 'first-789fb.firebasestorage.app',
    iosBundleId: 'com.example.clothApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMxsjZy3lCqnSeI5cRoEyUqoDGP4UBsSA',
    appId: '1:964323096567:web:1bfd9cad244de2fe12e0f2',
    messagingSenderId: '964323096567',
    projectId: 'first-789fb',
    authDomain: 'first-789fb.firebaseapp.com',
    databaseURL: 'https://first-789fb-default-rtdb.firebaseio.com',
    storageBucket: 'first-789fb.firebasestorage.app',
    measurementId: 'G-VWH3TY9N6R',
  );
}
